import { Metadata } from "next";
import React, { Children, ReactNode } from "react";

export const metadata: Metadata = {
  title: "FACEBOX",
  description: "Generated by create next app",
};

const rootlayout = ({ children }: { children: ReactNode }) => {
  return <main>{children}</main>;
};

export default rootlayout;
